// ─── 86b.ai Full Services & Solutions Catalog ───────────────────────────────
// Sourced from Sample Content.docx + existing 86b.ai services

export interface ServiceStep { title: string; desc: string; }
export interface ServiceFeature { title: string; desc: string; }
export interface ServiceMetric { value: string; label: string; sub: string; }

export interface Service {
  slug: string;
  tag: string;
  category: string;
  icon: string;
  image: string;
  title: string;
  headline: string;
  summary: string;
  description: string;
  problem: string;
  steps: ServiceStep[];
  features: ServiceFeature[];
  metrics: ServiceMetric[];
  techStack: string[];
  ctaLabel: string;
}

export const services: Service[] = [
  // ── CORE SERVICES (from existing 86b.ai work) ────────────────────────────
  {
    slug: "generative-ai",
    tag: "Generative AI",
    category: "Core AI",
    icon: "Cpu",
    image: "/svc_genai.png",
    title: "Enterprise Generative AI",
    headline: "Deploy private LLMs trained on your proprietary knowledge — not the public internet.",
    summary: "Fine-tune and deploy private LLMs (GPT, Claude, Llama) against your company's internal knowledge base for secure, accurate, enterprise-grade AI assistants.",
    description: "We deploy and fine-tune large language models against your proprietary documentation, product data, and institutional knowledge — giving your teams an AI assistant that knows your business, stays inside your security boundary, and never exposes data to public APIs.",
    problem: "Generic AI tools don't know your business. Employees waste hours reformulating the same queries, getting generic answers, and manually cross-referencing internal documents. A private LLM trained on your knowledge base solves this at scale.",
    steps: [
      { title: "Knowledge Audit", desc: "We catalogue all internal knowledge sources: documentation, wikis, SOPs, product specs, and customer data." },
      { title: "Data Pipeline & Embedding", desc: "Documents are cleaned, chunked, embedded, and stored in your private vector database." },
      { title: "Model Fine-tuning & RAG", desc: "We fine-tune or configure your chosen LLM with RAG retrieval against your knowledge store." },
      { title: "Deployment & Integration", desc: "The AI assistant is deployed inside your infrastructure and connected to your internal tools and workflows." },
    ],
    features: [
      { title: "Private deployment", desc: "Your LLM runs inside your environment — no data leaves your network." },
      { title: "RAG-powered accuracy", desc: "Answers are grounded in your actual documents, not hallucinated from training data." },
      { title: "Source citations", desc: "Every response cites the source document so employees can verify and trust outputs." },
      { title: "Multi-model support", desc: "GPT-4o, Claude 3.5, Llama 3, Mistral — we deploy the best fit for your use case and budget." },
      { title: "Role-based access", desc: "Different teams see different knowledge — finance sees financial docs, legal sees legal docs." },
      { title: "Continuous learning", desc: "New documents automatically update the knowledge base — the system never goes stale." },
    ],
    metrics: [
      { value: "85%", label: "Query Resolution", sub: "Internal queries resolved without human escalation" },
      { value: "10×", label: "Faster", sub: "Knowledge retrieval vs. manual search" },
      { value: "100%", label: "Private", sub: "Zero exposure to public AI APIs" },
    ],
    techStack: ["GPT-4o", "Claude 3.5", "Llama 3", "LangChain", "Pinecone", "FastAPI"],
    ctaLabel: "Deploy Your Private LLM",
  },
  {
    slug: "digital-humans",
    tag: "Conversational AI",
    category: "Core AI",
    icon: "Bot",
    image: "/svc_digital_human.png",
    title: "Digital Human Agents",
    headline: "Lifelike AI avatars that represent your brand 24/7 with 0.3s response latency.",
    summary: "Conversational digital humans programmed with your brand voice, product knowledge, and support workflows — resolving 94% of customer queries without human intervention.",
    description: "We build photorealistic or stylized digital human agents that speak, listen, and respond with human-like fluency. Each agent is programmed with your company's brand guidelines, product documentation, and support procedures — delivering a premium, always-available interaction experience across web, kiosk, and mobile.",
    problem: "Enterprise support teams are overwhelmed with repetitive first-line queries. Standard chatbots feel robotic and damage brand perception. Customers expect instant, intelligent, empathetic responses — at any hour, in any language.",
    steps: [
      { title: "Brand Voice Profiling", desc: "We extract your brand tone, vocabulary, and personality to program the agent's conversational style." },
      { title: "Knowledge Base Ingestion", desc: "Product docs, FAQs, and support history are ingested into a secure RAG pipeline." },
      { title: "Avatar Build & Integration", desc: "The digital human is rendered and integrated via WebRTC into your platform." },
      { title: "Continuous Improvement", desc: "Conversation logs are analyzed to improve response quality over time." },
    ],
    features: [
      { title: "0.32s average response latency", desc: "Near-real-time voice and text that feels genuinely conversational." },
      { title: "40+ language support", desc: "English, German, French, Arabic, Hindi, and more — deploy globally." },
      { title: "Emotion & intent detection", desc: "Agent adapts tone based on customer sentiment — more empathetic when frustrated." },
      { title: "CRM & ticketing integration", desc: "Seamlessly hands off to human agents with full context preserved." },
      { title: "Custom avatar design", desc: "Photorealistic or branded 3D character matching your identity." },
      { title: "Secure knowledge containment", desc: "All RAG queries run on-premise or in private VPC — your data never leaves." },
    ],
    metrics: [
      { value: "94%", label: "Resolution Rate", sub: "Customer queries resolved directly" },
      { value: "0.3s", label: "Latency", sub: "Average response time" },
      { value: "90%", label: "Cost Saving", sub: "Reduction in first-line support cost" },
    ],
    techStack: ["WebRTC", "ElevenLabs", "GPT-4o", "Pinecone", "LangChain", "React"],
    ctaLabel: "Deploy Your Digital Human",
  },
  {
    slug: "intelligent-process-automation",
    tag: "Process Automation",
    category: "Core AI",
    icon: "Workflow",
    image: "/svc_automation.png",
    title: "Intelligent Process Automation",
    headline: "Automate unstructured workflows — invoices, documents, approvals — without human intervention.",
    summary: "Combine AI with Robotic Process Automation (RPA) to eliminate manual handling of invoices, document routing, compliance checks, and approval workflows at enterprise scale.",
    description: "We combine AI document understanding with RPA execution to automate the workflows that traditional automation can't touch — unstructured PDFs, handwritten forms, email-based approvals, and multi-system routing chains. Your team stops handling paper and starts handling exceptions.",
    problem: "Traditional RPA breaks on unstructured data. Invoice formats change, email approvals vary, and exception handling requires human judgment. AI-powered automation solves this by understanding content, not just structure.",
    steps: [
      { title: "Workflow Mapping", desc: "We document every manual step, decision point, and exception in your target process." },
      { title: "AI Document Understanding", desc: "Intelligent Document Processing (IDP) extracts structured data from any document format." },
      { title: "Automation Build", desc: "RPA bots execute the workflow steps while AI handles decision-making and exception routing." },
      { title: "Monitoring & Escalation", desc: "Low-confidence decisions are routed to human review — everything else runs automatically." },
    ],
    features: [
      { title: "Unstructured document handling", desc: "PDFs, scans, emails, handwritten forms — extracted and structured automatically." },
      { title: "Multi-system integration", desc: "Works across SAP, Salesforce, Oracle, and custom internal systems simultaneously." },
      { title: "Exception-based human review", desc: "Humans only see edge cases — routine processing is fully automated." },
      { title: "Audit trail generation", desc: "Every automated decision is logged with evidence for compliance review." },
      { title: "99.9% uptime SLA", desc: "Self-healing automation pipelines with automated failure recovery." },
      { title: "ROI measurement dashboard", desc: "Real-time dashboard showing hours saved and error rates reduced." },
    ],
    metrics: [
      { value: "80%", label: "Time Saved", sub: "Reduction in manual processing hours" },
      { value: "99.9%", label: "Uptime", sub: "Automated pipeline availability" },
      { value: "<2s", label: "Processing", sub: "Per document extraction time" },
    ],
    techStack: ["GPT-4o", "Unstructured.io", "UiPath", "Python", "LangChain", "PostgreSQL"],
    ctaLabel: "Automate Your Workflows",
  },
  {
    slug: "revenue-tracking",
    tag: "Financial Intelligence",
    category: "Finance AI",
    icon: "BarChart3",
    image: "/svc_revenue.png",
    title: "Revenue Tracking & Auditing",
    headline: "Recover lost revenue by auditing every invoice, contract, and billing line automatically.",
    summary: "AI that ingests invoices, POs, and master service agreements at scale — flagging billing discrepancies, contract breaches, and revenue leakage in seconds, not weeks.",
    description: "Our revenue intelligence platform ingests thousands of financial documents simultaneously, extracts structured data from unstructured PDFs, and cross-references every billing line against your master agreements and pricing schedules. Revenue leakage is flagged instantly with full audit trails.",
    problem: "Enterprise finance teams audit invoices manually, leaving significant revenue leakage undetected. Billing errors, contract covenant breaches, and pricing discrepancies cost large organizations hundreds of thousands annually — often unnoticed for quarters.",
    steps: [
      { title: "Document Ingestion", desc: "Invoices, POs, and MSAs are ingested at scale — PDFs, scans, and digital formats all supported." },
      { title: "Intelligent Extraction", desc: "AI extracts line-item data, pricing terms, payment schedules, and contract covenants automatically." },
      { title: "Cross-Reference Audit", desc: "Every billing line is matched against your master agreements and approved pricing schedules." },
      { title: "Leakage Reports", desc: "Flagged discrepancies surface in structured audit reports with recovery recommendations." },
    ],
    features: [
      { title: "1,000+ docs/minute", desc: "Ingest entire invoice archives in minutes, not weeks." },
      { title: "MSA covenant matching", desc: "Identifies when billing terms deviate from your signed master agreements." },
      { title: "ERP reconciliation", desc: "Syncs findings back to SAP, NetSuite, or QuickBooks ledger directly." },
      { title: "Duplicate & overpayment detection", desc: "Flags duplicate invoices and overpayments with high confidence scoring." },
      { title: "Audit trail generation", desc: "Every decision logged with evidence for your CFO and external auditors." },
      { title: "Escalation workflows", desc: "High-value discrepancies auto-routed to the right finance team member." },
    ],
    metrics: [
      { value: "$42K+", label: "Avg. Recovery", sub: "Annual revenue leakage recovered" },
      { value: "90%", label: "Time Saved", sub: "Reduction in manual audit hours" },
      { value: "99.9%", label: "Accuracy", sub: "Extraction accuracy on financial docs" },
    ],
    techStack: ["GPT-4o", "Unstructured.io", "LangChain", "PostgreSQL", "SAP API", "Python"],
    ctaLabel: "Start Revenue Auditing",
  },
  {
    slug: "predictive-analytics",
    tag: "Predictive Intelligence",
    category: "Finance AI",
    icon: "TrendingUp",
    image: "/svc_predictive.png",
    title: "Predictive Analytics & Forecasting",
    headline: "Know what's coming before it arrives — revenue, inventory, risk, and demand.",
    summary: "Machine learning models that ingest historical data, market signals, and macroeconomic indicators to generate highly accurate revenue, inventory, and financial forecasts.",
    description: "We build custom predictive models trained on your historical business data that forecast revenue, demand, financial risk, inventory needs, and equipment maintenance schedules — giving your leadership team decision-ready intelligence weeks before competitors act.",
    problem: "Business decisions made on last quarter's reports are already outdated. Leaders need forward-looking intelligence — not dashboards of what already happened. Manual forecasting processes are slow, inconsistent, and don't account for market signals beyond your own data.",
    steps: [
      { title: "Data Source Integration", desc: "We connect to your ERP, CRM, market feeds, and external data sources." },
      { title: "Model Development", desc: "Custom ML models are trained on your historical data with external signal enrichment." },
      { title: "Forecast Engine Deployment", desc: "The prediction engine is deployed inside your environment with a real-time dashboard." },
      { title: "Accuracy Monitoring", desc: "Model accuracy is tracked continuously and retrained as new data accumulates." },
    ],
    features: [
      { title: "Revenue forecasting", desc: "Predict quarterly revenue with higher accuracy than traditional financial models." },
      { title: "Demand & inventory prediction", desc: "Optimize stock levels and procurement by forecasting demand weeks ahead." },
      { title: "Predictive maintenance", desc: "Predict equipment failure before it happens — reduce unplanned downtime." },
      { title: "Financial risk modeling", desc: "Identify credit risk, cash flow gaps, and market exposure proactively." },
      { title: "Scenario analysis", desc: "Run what-if scenarios to understand the impact of business decisions before making them." },
      { title: "ERP & BI integration", desc: "Forecast outputs flow directly into your existing reporting and planning tools." },
    ],
    metrics: [
      { value: "92%", label: "Forecast Accuracy", sub: "Revenue prediction accuracy rate" },
      { value: "3×", label: "Faster", sub: "Planning cycles vs. manual methods" },
      { value: "30%", label: "Cost Reduction", sub: "Inventory overstock & stockout costs" },
    ],
    techStack: ["Python", "XGBoost", "Prophet", "TensorFlow", "Databricks", "Snowflake"],
    ctaLabel: "Build Your Forecast Engine",
  },
  {
    slug: "data-organization",
    tag: "Investor Readiness",
    category: "Finance AI",
    icon: "Briefcase",
    image: "/svc_investor.png",
    title: "Data Organization & Investor Readiness",
    headline: "Transform scattered corporate data into VC-ready structures in days.",
    summary: "Organize unlisted cap tables, scattered contracts, and operational data into clean, investor-ready packages. Compress due diligence from months to days.",
    description: "We deploy AI to ingest and structure your scattered corporate documentation — cap tables, shareholder agreements, operational reports, financial statements, and compliance records — into clean, standardized data packages that match the due diligence requirements of PE firms and VCs.",
    problem: "Companies seeking funding lose deals because their data is scattered. Investors lose confidence when due diligence takes weeks and uncovers disorganized records. Founders waste months preparing data rooms manually.",
    steps: [
      { title: "Data Audit & Collection", desc: "We identify and ingest all scattered data — drives, emails, legacy DBs, and paper records." },
      { title: "AI Structuring", desc: "Documents are classified, extracted, and mapped into standardized legal and financial schemas." },
      { title: "Data Room Construction", desc: "A clean, navigable investor data room is built with all documents properly indexed." },
      { title: "Investor Matching", desc: "Company metrics are cross-referenced against LP investment mandates to identify best-fit investors." },
    ],
    features: [
      { title: "4,500+ document processing", desc: "Handles large document volumes across multiple formats and source systems." },
      { title: "Cap table normalization", desc: "Converts messy spreadsheet cap tables into investor-ready legal structures." },
      { title: "SOC2 compliance structuring", desc: "Organizes data to meet SOC2 audit requirements as a byproduct of investor preparation." },
      { title: "Investor mandate matching", desc: "AI matches your company profile against databases of PE/VC investment criteria." },
      { title: "NDA-protected processing", desc: "All processing occurs under strict NDA with zero data sharing." },
      { title: "Ongoing data governance", desc: "Sets up document management workflows to keep your data room current." },
    ],
    metrics: [
      { value: "10×", label: "Faster", sub: "Due diligence preparation time" },
      { value: "4,500+", label: "Documents", sub: "Avg. files processed per engagement" },
      { value: "94.8%", label: "Match Score", sub: "Investor alignment accuracy" },
    ],
    techStack: ["GPT-4o", "Unstructured.io", "LangChain", "Pinecone", "PostgreSQL", "Python"],
    ctaLabel: "Prepare for Funding",
  },
  {
    slug: "nlp-solutions",
    tag: "Natural Language AI",
    category: "Advanced AI",
    icon: "Search",
    image: "/svc_nlp.png",
    title: "NLP & Document Intelligence",
    headline: "Extract insight from unstructured text at enterprise scale — contracts, reports, emails.",
    summary: "Sentiment analysis, document classification, text summarization, and contract intelligence — applied to your document archives to surface insight that was previously invisible.",
    description: "We build NLP pipelines that process your unstructured text at scale: classifying thousands of documents automatically, summarizing lengthy reports into executive briefs, extracting key clauses from contracts, and analyzing customer sentiment across support channels — turning text noise into structured intelligence.",
    problem: "Enterprises generate vast amounts of unstructured text — contracts, customer emails, support tickets, research reports — and most of it is never analyzed. Critical insight is buried in documents no one has time to read.",
    steps: [
      { title: "Text Source Mapping", desc: "We identify all unstructured text sources: email archives, document stores, CRM notes, support logs." },
      { title: "NLP Pipeline Design", desc: "Custom NLP models are configured for your specific classification and extraction needs." },
      { title: "Deployment & Integration", desc: "The pipeline runs on your documents continuously, feeding structured output to your dashboards." },
      { title: "Human-in-the-loop Review", desc: "Low-confidence classifications route to human review — high-confidence outputs flow automatically." },
    ],
    features: [
      { title: "Contract clause extraction", desc: "Identify obligation, liability, termination, and renewal clauses across thousands of contracts." },
      { title: "Sentiment analysis at scale", desc: "Analyze customer sentiment across email, chat, reviews, and support tickets." },
      { title: "Automated document classification", desc: "Route incoming documents to the right teams without manual triage." },
      { title: "Multi-language support", desc: "Process documents in 40+ languages with consistent accuracy." },
      { title: "Text summarization", desc: "Generate executive summaries of lengthy reports, legal documents, and research papers." },
      { title: "Entity extraction", desc: "Extract people, organizations, dates, amounts, and custom entities from any document." },
    ],
    metrics: [
      { value: "97%", label: "Classification Accuracy", sub: "Document routing precision" },
      { value: "100×", label: "Throughput", sub: "Documents processed vs. manual review" },
      { value: "40+", label: "Languages", sub: "Supported for text processing" },
    ],
    techStack: ["spaCy", "Hugging Face", "GPT-4o", "LangChain", "Elasticsearch", "FastAPI"],
    ctaLabel: "Build Your NLP Pipeline",
  },
  {
    slug: "computer-vision",
    tag: "Visual AI",
    category: "Advanced AI",
    icon: "Layers",
    image: "/svc_vision.png",
    title: "Computer Vision Solutions",
    headline: "AI that sees, identifies, and acts — from quality inspection to medical imaging.",
    summary: "Object detection, quality inspection, facial recognition, and medical image analysis — custom computer vision models trained on your domain-specific visual data.",
    description: "We build and deploy custom computer vision systems for manufacturing quality control, retail shelf analysis, medical imaging assistance, security surveillance, and document digitization — replacing slow, error-prone manual visual inspection with real-time AI analysis.",
    problem: "Manual visual inspection is slow, inconsistent, and doesn't scale. A quality inspector misses defects after hours of repetitive work. A radiologist reviewing hundreds of scans per day faces cognitive fatigue. Computer vision solves this with consistent, high-speed analysis.",
    steps: [
      { title: "Use Case Definition", desc: "We define exactly what the model needs to detect, classify, or measure in your visual data." },
      { title: "Data Collection & Labeling", desc: "We work with your visual data or help collect and label training datasets." },
      { title: "Model Training & Validation", desc: "Custom CV models are trained and validated against your specific visual domain." },
      { title: "Edge or Cloud Deployment", desc: "Models are deployed on cameras, edge devices, or cloud infrastructure based on your needs." },
    ],
    features: [
      { title: "Manufacturing quality inspection", desc: "Detect surface defects, assembly errors, and dimensional deviations on production lines." },
      { title: "Medical imaging assistance", desc: "Pre-screen X-rays, MRIs, and CT scans to highlight potential anomalies for radiologist review." },
      { title: "Retail shelf analytics", desc: "Monitor product placement, stock levels, and planogram compliance in real time." },
      { title: "Document digitization", desc: "Convert handwritten forms, tables, and printed documents into structured digital data." },
      { title: "Edge AI deployment", desc: "Deploy vision models directly on cameras and IoT devices for real-time on-device inference." },
      { title: "Real-time alerting", desc: "Immediate alerts when the model detects defects, anomalies, or threshold breaches." },
    ],
    metrics: [
      { value: "99.2%", label: "Detection Rate", sub: "Defect and anomaly detection accuracy" },
      { value: "30ms", label: "Inference Time", sub: "Per frame analysis latency" },
      { value: "60%", label: "Defect Reduction", sub: "Manufacturing defect escape rate" },
    ],
    techStack: ["PyTorch", "YOLO", "OpenCV", "TensorRT", "Docker", "NVIDIA Triton"],
    ctaLabel: "Build Your Vision System",
  },
  {
    slug: "german-training",
    tag: "Workforce AI",
    category: "Workforce AI",
    icon: "BookOpen",
    image: "/svc_german.png",
    title: "AI German Language Training",
    headline: "Prepare your workforce for German placements with AI-powered language coaching.",
    summary: "Personalized AI language coaching for aspirants targeting German careers — simulates native interviews, tracks CEFR progress, and connects top performers with Berlin and Munich recruiters.",
    description: "Our AI German training engine is purpose-built for professionals seeking employment in Germany. It extracts role-specific vocabulary from real German job postings, conducts simulated native-speaker technical interviews, scores pronunciation and grammar in real time, and maps progress to CEFR standards.",
    problem: "International professionals struggle to reach German B2/C1 language standards needed for employment. Generic language apps don't teach business German or simulate German corporate interview culture. Candidates spend years in self-study with no structured pathway to placement.",
    steps: [
      { title: "Role & Industry Profiling", desc: "We extract German vocabulary from real job postings matching the candidate's target role." },
      { title: "Adaptive Learning Path", desc: "A personalized curriculum is built based on current CEFR level, target industry, and timeline." },
      { title: "Native Interview Simulation", desc: "AI simulates realistic German business interviews, scoring grammar, vocabulary, and pronunciation." },
      { title: "Recruiter Matching", desc: "Top performers are connected directly with our network of German employers." },
    ],
    features: [
      { title: "CEFR-aligned curriculum", desc: "Structured tracks from A2 to C1 with automated level assessment." },
      { title: "98% pronunciation accuracy scoring", desc: "Real-time phoneme analysis vs. native German speech patterns." },
      { title: "Industry-specific vocabulary", desc: "Engineering, IT, healthcare, finance — vocabulary modules per sector." },
      { title: "Unlimited mock interviews", desc: "AI-conducted mock interviews with detailed feedback reports." },
      { title: "Progress analytics dashboard", desc: "Exportable progress reports for candidates, employers, and coordinators." },
      { title: "German employer network", desc: "Access to verified German employers for high-performing candidates." },
    ],
    metrics: [
      { value: "85%", label: "Pass Rate", sub: "Interview success rate for trained candidates" },
      { value: "98%", label: "Pronunciation", sub: "Accuracy scoring vs. native speakers" },
      { value: "B2/C1", label: "CEFR Target", sub: "Standard reached within 6 months" },
    ],
    techStack: ["Whisper AI", "GPT-4o", "ElevenLabs", "FastAPI", "PostgreSQL", "React"],
    ctaLabel: "Start Language Training",
  },
  {
    slug: "hr-ai",
    tag: "Talent Intelligence",
    category: "Workforce AI",
    icon: "Users",
    image: "/svc_hr.png",
    title: "HR & Talent AI Solutions",
    headline: "Hire faster, retain longer — AI that screens thousands of CVs and predicts flight risk.",
    summary: "Intelligent talent matching, employee sentiment analysis, and AI-powered onboarding copilots that reduce time-to-hire by 60% and improve retention through early warning systems.",
    description: "We deploy AI across the complete HR lifecycle — from screening thousands of resumes in seconds to predicting which employees are likely to leave before they hand in notice. Our HR AI solutions remove bias from hiring, surface skill gaps in real time, and give new hires a 24/7 onboarding assistant.",
    problem: "HR teams manually screen hundreds of CVs for each role, introduce unconscious bias at every step, and learn about retention issues only after employees resign. Skill gaps accumulate undetected until they become critical business problems.",
    steps: [
      { title: "ATS Integration", desc: "We connect to your existing Applicant Tracking System and HRIS for data access." },
      { title: "Talent Matching Model", desc: "NLP models screen and rank candidates against role requirements and cultural fit signals." },
      { title: "Sentiment & Retention Analytics", desc: "Anonymized analysis of internal communications and feedback data surfaces early flight risk." },
      { title: "Onboarding Copilot Deployment", desc: "Conversational AI assistant deployed for new hires via Slack, Teams, or web." },
    ],
    features: [
      { title: "Resume screening at scale", desc: "Screen thousands of CVs in seconds with NLP-powered skill and experience matching." },
      { title: "Bias reduction", desc: "Structured scoring removes demographic bias from initial candidate evaluation." },
      { title: "Employee sentiment monitoring", desc: "Anonymized text analysis of surveys and feedback gauges workplace morale trends." },
      { title: "Flight risk prediction", desc: "ML models predict which employees are at retention risk 60–90 days before resignation." },
      { title: "Skill gap mapping", desc: "Real-time analysis of organizational skill coverage and emerging capability shortfalls." },
      { title: "Smart onboarding copilot", desc: "24/7 AI assistant for new hires covering policies, procedures, and operational questions." },
    ],
    metrics: [
      { value: "60%", label: "Faster Hiring", sub: "Reduction in time-to-hire" },
      { value: "40%", label: "Turnover Reduction", sub: "With early intervention on flight risk" },
      { value: "90%", label: "HR Time Saved", sub: "On initial CV screening stage" },
    ],
    techStack: ["spaCy", "Hugging Face", "GPT-4o", "Workday API", "PostgreSQL", "Slack API"],
    ctaLabel: "Transform Your HR Function",
  },
  {
    slug: "ai-governance",
    tag: "Risk & Compliance",
    category: "AI Governance",
    icon: "ShieldCheck",
    image: "/svc_governance.png",
    title: "AI Governance & Compliance",
    headline: "Audit, explain, and govern your AI systems before regulators do.",
    summary: "Bias detection, explainable AI dashboards, automated regulatory compliance monitoring (EU AI Act, GDPR, HIPAA), and model lineage tracking for enterprise AI governance.",
    description: "As AI regulation accelerates globally, enterprises need robust governance frameworks before deployment — not after an incident. We implement bias & fairness auditing, explainable AI dashboards, automated compliance monitoring against evolving regulations, and full model lineage tracking.",
    problem: "Enterprises deploying AI without governance frameworks face regulatory risk, reputational damage, and potential fines under the EU AI Act, GDPR, and HIPAA. Black-box AI decisions can't be audited, defended in court, or explained to regulators.",
    steps: [
      { title: "AI System Inventory", desc: "We catalogue all AI systems in production: what they do, what data they use, and who they affect." },
      { title: "Bias & Risk Assessment", desc: "Automated scanning of models and data pipelines for bias, fairness violations, and data quality issues." },
      { title: "Governance Framework Implementation", desc: "We build XAI dashboards, audit logs, and compliance monitoring workflows tailored to your regulatory context." },
      { title: "Ongoing Monitoring", desc: "Continuous scanning tracks model drift, regulatory changes, and new risk signals." },
    ],
    features: [
      { title: "Bias & fairness auditing", desc: "Continuous scanning of algorithms for demographic and systemic bias." },
      { title: "Explainable AI dashboards", desc: "Translates black-box model decisions into clear, auditable explanations." },
      { title: "EU AI Act compliance", desc: "Maps your AI systems against EU AI Act risk tiers and compliance requirements." },
      { title: "GDPR & HIPAA mapping", desc: "Automated compliance tracking against data privacy and healthcare regulations." },
      { title: "Model lineage tracking", desc: "Full provenance tracking of training data, model versions, and deployment history." },
      { title: "Automated regulatory monitoring", desc: "AI monitors evolving global regulations and flags when your systems need updating." },
    ],
    metrics: [
      { value: "100%", label: "Audit Coverage", sub: "All AI systems inventoried and governed" },
      { value: "EU AI Act", label: "Compliant", sub: "Mapped to all risk tiers" },
      { value: "Real-time", label: "Monitoring", sub: "Continuous compliance scanning" },
    ],
    techStack: ["Giskard", "IBM OpenScale", "MLflow", "Python", "Grafana", "Custom XAI"],
    ctaLabel: "Govern Your AI Systems",
  },
  {
    slug: "ai-testing",
    tag: "QA & Red-Teaming",
    category: "AI Governance",
    icon: "FlaskConical",
    image: "/svc_testing.png",
    title: "AI App Testing & Red-Teaming",
    headline: "Red-team your AI applications before your users — or regulators — find the flaws.",
    summary: "Automated adversarial testing with 10,000+ stress inputs, hallucination detection, bias measurement, and SOC2/HIPAA compliance reporting for enterprise AI applications.",
    description: "Before your AI application goes live, it needs adversarial stress testing, hallucination evaluation, bias assessment, and compliance validation. Our QA engine does all of this automatically — producing a compliance-ready audit report your security team and regulators will accept.",
    problem: "Enterprise AI applications that haven't been adversarially tested are a liability. A single hallucinated response or data leak can cost organizations millions in fines and reputational damage. Most teams lack the tooling and expertise to test AI systems properly before deployment.",
    steps: [
      { title: "Application Profiling", desc: "We analyze your AI app's inputs, outputs, system prompts, and data access patterns." },
      { title: "Adversarial Testing", desc: "10,000+ crafted prompts probe hallucination, jailbreak, and data leak vulnerabilities." },
      { title: "Bias & Fairness Evaluation", desc: "Outputs are analyzed across demographic and linguistic dimensions for bias patterns." },
      { title: "Compliance Reporting", desc: "A full audit report covers SOC2, HIPAA, GDPR, and EU AI Act requirements." },
    ],
    features: [
      { title: "10,000+ adversarial test cases", desc: "Comprehensive stress testing covering jailbreaks, prompt injections, and boundary probing." },
      { title: "Hallucination rate measurement", desc: "Quantified hallucination rate with evidence samples for review." },
      { title: "Bias detection", desc: "Evaluates outputs for gender, racial, cultural, and linguistic bias patterns." },
      { title: "Model drift monitoring", desc: "Ongoing monitoring detects when model behavior degrades after deployment." },
      { title: "SOC2 & HIPAA audit reports", desc: "Compliance-ready documentation acceptable to regulators." },
      { title: "Remediation recommendations", desc: "Actionable fixes for every identified vulnerability, ranked by severity." },
    ],
    metrics: [
      { value: "0.02%", label: "Target Rate", sub: "Hallucination boundary we target" },
      { value: "10K+", label: "Test Cases", sub: "Adversarial inputs per evaluation" },
      { value: "SOC2", label: "Compliant", sub: "Audit-ready reporting standard" },
    ],
    techStack: ["Giskard", "DeepEval", "LangChain", "Python", "OpenAI Evals", "Custom Agents"],
    ctaLabel: "Test Your AI Application",
  },
  {
    slug: "llm-orchestration",
    tag: "AI Infrastructure",
    category: "MLOps & Infrastructure",
    icon: "Network",
    image: "/svc_llm_infra.png",
    title: "LLM Orchestration & RAG Infrastructure",
    headline: "Private, secure AI pipelines connecting your LLMs to your enterprise data.",
    summary: "End-to-end AI infrastructure: local or hosted LLMs, vector search pipelines, RAG architecture, agent orchestration, and self-healing data sync — all inside your own environment.",
    description: "We design and deploy the full AI infrastructure stack — from model selection and deployment (local Llama, hosted GPT, or custom fine-tuned) to vector databases, RAG pipelines, orchestration layers, and production monitoring. Your data never leaves your environment.",
    problem: "Enterprises want AI but can't send sensitive data to public APIs. Building private AI infrastructure requires deep expertise in model deployment, vector databases, prompt engineering, and MLOps — skills most internal teams don't yet have.",
    steps: [
      { title: "Architecture Design", desc: "We design the full stack: model choice, embedding strategy, vector store, orchestration, and API layer." },
      { title: "Model Deployment", desc: "Deploy Llama, Mistral, or custom fine-tuned models on-premise or in your private VPC." },
      { title: "RAG Pipeline Build", desc: "Documents are chunked, embedded, and stored in a vector database for semantic retrieval." },
      { title: "Orchestration & Monitoring", desc: "LangChain or custom orchestration with full observability and self-healing." },
    ],
    features: [
      { title: "Local & hosted model support", desc: "Deploy Llama 3, Mistral, Gemma, GPT-4, or custom fine-tuned models." },
      { title: "Private vector databases", desc: "Pinecone, Weaviate, Chroma, or pgvector inside your infrastructure." },
      { title: "Multi-source RAG", desc: "Ingest PDFs, databases, APIs, wikis, and email archives into unified retrieval." },
      { title: "Agent orchestration", desc: "Multi-step AI agents that query databases, call APIs, and take actions autonomously." },
      { title: "Self-healing pipelines", desc: "Automated health checks and fallback logic keep your AI stack running 24/7." },
      { title: "Zero public API exposure", desc: "All processing inside your network — no data transmitted to third-party APIs." },
    ],
    metrics: [
      { value: "100%", label: "Private", sub: "Zero data exposure to public APIs" },
      { value: "<2s", label: "Retrieval", sub: "Average RAG query response time" },
      { value: "99.9%", label: "Uptime", sub: "Self-healing pipeline availability" },
    ],
    techStack: ["Llama 3", "Mistral", "LangChain", "Pinecone", "Weaviate", "FastAPI", "Kubernetes"],
    ctaLabel: "Build Your AI Infrastructure",
  },
  {
    slug: "mlops",
    tag: "MLOps",
    category: "MLOps & Infrastructure",
    icon: "Activity",
    image: "/svc_mlops.png",
    title: "MLOps & AI Lifecycle Management",
    headline: "Keep your AI in production — monitored, maintained, and always improving.",
    summary: "CI/CD pipelines for machine learning, model drift monitoring, automated retraining, cloud integration (AWS, Azure, GCP), and production-grade model serving infrastructure.",
    description: "Deploying a model is the beginning, not the end. We implement the full MLOps lifecycle — experiment tracking, CI/CD pipelines, model versioning, drift detection, automated retraining triggers, and production monitoring — ensuring your AI stays accurate and reliable long after launch.",
    problem: "Most organizations deploy ML models and then watch them degrade silently as data distribution shifts. Without MLOps, models become liabilities: inaccurate outputs that no one notices until something breaks publicly.",
    steps: [
      { title: "Current State Assessment", desc: "We audit your existing model deployment and monitoring practices." },
      { title: "MLOps Platform Setup", desc: "CI/CD pipelines for ML, experiment tracking, model registry, and version control." },
      { title: "Monitoring & Alerting", desc: "Real-time monitoring of model accuracy, data drift, and infrastructure health." },
      { title: "Automated Retraining", desc: "Triggered retraining pipelines that maintain model accuracy as data evolves." },
    ],
    features: [
      { title: "CI/CD for machine learning", desc: "Automated testing, validation, and deployment pipelines for ML models." },
      { title: "Model drift detection", desc: "Real-time alerts when model performance degrades beyond defined thresholds." },
      { title: "Experiment tracking", desc: "MLflow or W&B integration for full experiment reproducibility." },
      { title: "Multi-cloud deployment", desc: "AWS SageMaker, Azure AI Studio, or Google Vertex AI — or hybrid on-premise." },
      { title: "Model serving optimization", desc: "ONNX, NVIDIA Triton, and Ray Serve for optimized, scalable model serving." },
      { title: "Governance & audit trails", desc: "Full lineage tracking of model versions, training data, and deployment history." },
    ],
    metrics: [
      { value: "99.9%", label: "Model Uptime", sub: "Production model availability" },
      { value: "4×", label: "Faster Iteration", sub: "Model update cycle time" },
      { value: "Zero", label: "Drift Escapes", sub: "Undetected model degradation" },
    ],
    techStack: ["MLflow", "Kubeflow", "W&B", "AWS SageMaker", "Docker", "Kubernetes"],
    ctaLabel: "Implement MLOps",
  },
  {
    slug: "travel-planning",
    tag: "Logistics AI",
    category: "Industry Solutions",
    icon: "Globe",
    image: "/svc_travel.png",
    title: "AI Travel & Route Planning",
    headline: "Autonomous route optimization that cuts delays and logistics costs in real time.",
    summary: "Dynamic AI-powered logistics planning that cross-references port schedules, tariff exclusions, and tax codes in real time to cut transit delays by 30%.",
    description: "Our AI logistics engine ingests live data from shipping ports, customs databases, carrier schedules, and tax authority feeds to continuously optimize routing decisions. Whether managing corporate travel or international cargo, the system finds the fastest, cheapest, and most compliant path automatically.",
    problem: "Logistics planning teams spend hours manually cross-referencing schedules, tariff codes, and port availability. Errors lead to costly delays, customs holds, and missed delivery windows that damage client relationships.",
    steps: [
      { title: "Data Source Integration", desc: "We connect to your logistics systems, port APIs, carrier feeds, and customs databases." },
      { title: "Route Intelligence Engine", desc: "AI builds a real-time optimization model covering routes, costs, tariffs, and transit times." },
      { title: "Automated Decision Layer", desc: "System generates optimized routing decisions and flags exceptions for human review." },
      { title: "ERP Sync & Reporting", desc: "All decisions are logged and synced back into SAP, Oracle, or custom ERP." },
    ],
    features: [
      { title: "Live port & carrier data", desc: "Real-time feeds from major global ports, airlines, and logistics carriers." },
      { title: "Customs tariff matching", desc: "Automatic HTS code matching and tax-exemption identification." },
      { title: "Multi-modal routing", desc: "Optimizes across air, sea, rail, and road for cost and time efficiency." },
      { title: "Delay prediction", desc: "ML models predict likely delays based on historical congestion and weather data." },
      { title: "Compliance automation", desc: "Auto-generates customs declarations, manifests, and regulatory documentation." },
      { title: "SAP / Oracle integration", desc: "Bidirectional sync with major ERP systems for seamless operations." },
    ],
    metrics: [
      { value: "30%", label: "Fewer Delays", sub: "Reduction in port and transit delays" },
      { value: "14%", label: "Cost Cut", sub: "Average customs and routing savings" },
      { value: "12s", label: "Decision Speed", sub: "Full route optimization time" },
    ],
    techStack: ["Python", "OpenAI", "Apache Kafka", "PostgreSQL", "SAP API", "Custom ML"],
    ctaLabel: "Optimize Your Logistics",
  },
];

export const servicesBySlug: Record<string, Service> = Object.fromEntries(
  services.map((s) => [s.slug, s])
);

export const categories = [
  "All",
  "Core AI",
  "Finance AI",
  "Advanced AI",
  "Workforce AI",
  "AI Governance",
  "MLOps & Infrastructure",
  "Industry Solutions",
];

// Featured services shown on homepage (first 8)
export const featuredServices = services.slice(0, 8);
